export default {
NPPerushNotes:[
      {'author':"Nehemia Polen",'sefer':"Devarim",'chapter':"10",'verse':"12",
        'note':"The root 'yirah' precedes CREATION! The sense of RESPONSIBILITY for INFINITE POSSIBILITY",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Nehemia Polen",'sefer':"Devarim",'chapter':"10",'verse':"12",
        'note':"Yirah haRommuth = FEAR of G-d's GREATNESS = AWE: has an element of recoil and busha",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Nehemia Polen",'sefer':"Devarim",'chapter':"10",'verse':"12",
        'note':"The awe that G-d feels before creation 'present just before creation'. Yirah is a complete surrener to the Divine Presense within us? States of Ethereal contemplative possibility. This yirah precedes chochmah!",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Nehemia Polen",'sefer':"Devarim",'chapter':"10",'verse':"12",
        'note':"The HIGHEST which leads us to be ABSORBED into the DIVINE. The letters of thought which constantly permeate, shifting form, never ceasing - when we realize that these thoughts arise from G-d we nullify ourselves to the Origin....",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Nehemia Polen",'sefer':"Devarim",'chapter':"10",'verse':"12",
        'note':"When a person rises above the letters [forms] of thought, and is ABSORBED in G-d, then he can change anything [=perform miracles]. The person has an apotheosis - you are the master of the Shechina.",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Nehemia Polen",'sefer':"Shemot",'chapter':"1",'verse':"12",
        'note':"Beautiful, Awesome, Amazing!",
        'other':"Pri haAretz",'torahlink':"https://hebrewbooks.org/pdfpager.aspx?req=3134&st=&pgnum=51",'aboutlink':"https://101israel.com/rabbi-menachem-mendel-of-vitebsk/",'citation':"Parsha Zav"},
      {'author':"Lauri Wolff",'sefer':"Shemot",'chapter':"1",'verse':"12",
        'note':"Beautiful, Awesome, Amazing! And there's one other thing...",
        'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Sarah Henna Polen",'sefer':"Shemot",'chapter':"1",'verse':"12",
          'note':"Amazing! I never saw this before! Just like my father says... But look out for Greek Philosophy",
          'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Esti Polen",'sefer':"Shemot",'chapter':"1",'verse':"12",
          'note':"Just like my father says... But a little more care and consideration of the sick...",
          'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Adina Polen",'sefer':"Shemot",'chapter':"1",'verse':"12",
          'note':"Amazing! Just like my father says...with more art...",
          'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Nehemia Polen",'sefer':"Shemot",'chapter':"1",'verse':"13",
        'note':"What can I say? This is even better! I mean - you have to bring in this other torah! And that completely knocks out Amazon.",
        'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Nehemia Polen",'sefer':"Vayikra",'chapter':"23",'verse':"12",
        'note':"This is a 'fasten your seatbelts' moment!",
        'other':"",'torahlink':"",'aboutlink':"",'citation':""},
      {'author':"Nehemia Polen",'sefer':"Isaiah",'chapter':"15",'verse':"18",
        'note':"Though your sins be as scarlet (Shanim - read 'years'): if your sins are appropriate for your years - that is an older man is makpid on kavod, a younger man - women... - G-d says 'I understand that... ' but the other way around? There's a problem!",
        'other':"",'torahlink':"",'aboutlink':"",'citation':"interview: Rabbi Bind"},
      {'author':"Nehemia Polen",'sefer':"Bereishit",'chapter':"2",'verse':"20",
        'note':"lo matza ayzer k'neg'do: Why are women stronger then men? They have to be. If a stranger comes to the house, a man would give away everything!",
        'other':"",'torahlink':"",'aboutlink':"",'citation':"interview: Rabbi Bind"},
      {'author':"Nehemia Polen",'sefer':"Bamidbar",'chapter':"10",'verse':"25",
        'note':"See Rashi! Dan came last to 'sweep' up after everyone else. On the Hazon bicycle ride - there are two strong riders - one is the leader, and one is the 'sweep' who stays hidden, but shows up if you're having trouble!",
        'other':"",'torahlink':"",'aboutlink':"",'citation':"Rashi - here!"},
  ]
};
