export default {
"sefat_emet_np":
[
	{"Sefat_Emet,_Genesis,_Bereshit.1:1":[true,"Note: in this way he is in his place (Shabbos)"]},
	{"Sefat_Emet,_Genesis,_Bereshit.1:2":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.4:2":[true,"Check it out!"]},
	{"Sefat_Emet,_Genesis,_Bereshit.16:3":[true,"Note: Shabbos enables us to testify to the purposeness of creation"]},
	{"Sefat_Emet,_Genesis,_Bereshit.25:1":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.26:1":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.26:2":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.26:3":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.26:4":[true,"Note: As we act with Godly purpose, we are given wisdom, skill and energy to discern how to act, how to move forward."]},
	{"Sefat_Emet,_Genesis,_Bereshit.26:5":[true,""]},
	{"Sefat_Emet,_Genesis,_Bereshit.27:2":[true,"Note: Sheva Brachos Ellie Dubitsky (same'ach t'samach...)"]},
	{"Sefat_Emet,_Genesis,_Noach.4:1":[true,""]},
	{"Sefat_Emet,_Genesis,_Noach.15:2":[true,""]},
	{"Sefat_Emet,_Genesis,_Noach.33:2":[true,"This is the way of Torah - that he teaches l'adom laida l'chadesh derachim b'olam"]},
	{"Sefat_Emet,_Genesis,_Noach.34:1":[true,""]},
	{"Sefat_Emet,_Genesis,_Lech_Lecha.1:3":[true,"*Ramban - That is, the message goes out to EVERYONE but only Avraham heard it. Rabbi Twersky z'l - see Ta'anis 21 - Angels were speaking about R' Yohanan & Ilsa, but only R' Yohanan heard the convrersation so he concluded that the message was meant for him and he went back to learning"]},
	{"Sefat_Emet,_Genesis,_Lech_Lecha.3:4":[true,"WE HAVE THE DESIRE TO COME TO THE TRUE DESIRE - u'mi sh'ain lo ratzon k'rui yesh lo ratzon lavo l'ratzon emes"]},
	{"Sefat_Emet,_Genesis,_Lech_Lecha.4:1":[true,"Entering into Shabbos requires a surrender from the entaglements of this world. A jump - but then we may return to mend everything - even this world - and put it in its rightful place. [NP - this may describe every life descision - marriage] The disentanglement required by manuach IS an embarkation on a JOURNEY!"]},
	{"Sefat_Emet,_Genesis,_Lech_Lecha.5:4":[true,"haya b'zchus haran aviv - that is, THIS FAMILY - including Haran is already destined to be the channel of blessing"]},
	{"Sefat_Emet,_Genesis,_Vayera.1:2":[true,"af sh'hu k'hom hayom - sitting - situated in the physical world. Adina n'i"]},
	{"Sefat_Emet,_Genesis,_Vayera.2:1":[true,"Highlighting the last 4 lines: haShabbos... sh'lo amru ham'oneg..."]},
	{"Sefat_Emet,_Genesis,_Vayera.3:2":[true,"Radical acceptance - aval Mamre he'amin ki kach tzarich l'hios..."]},
	{"Sefat_Emet,_Genesis,_Vayera.13:2":[true,"Brackets and arrows... hamila hu atzmo inyan raiit panim... (to end)"]},
	{"Sefat_Emet,_Genesis,_Vayera.14:1":[true,"Brackets and arrows: perush sh'ze sh'yoshev hayinu ... (last 2 lines)"]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.1:3":[true,"SARAH DIDN'T (HAVE TO) PUSH AWAY THE DAYS OF HER YOUTH - SHE BUILT ON THEM!!"]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.1:4":[true,"perush on the mishnah: halomed yeled... v'ha'lomed zakein..."]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.3:2":[true,"Underline: kol ha'shanos sh'b'adom hu sh'HKBH poseach lvavo, tzarich sh'yika'vu b'l'vavo k'nal..."]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.4:1":[true,"underline: lachein tzarich ha'adom l'ros sh'y'hiye lo al kol panim ha'ara achas chadashe b'chol yom..."]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.5:4":[true,"T'hillim 69:14/ T'hillim 32:6; Proverbs: 12:2,8:35,18:22"]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.19:1":[true,"sh'nai chayai sarah means: the AGE of Sarah, the ERA of Sarah; she DEFINES the time period - just as we might say 'the PLACE of a great person'"]},
	{"Sefat_Emet,_Genesis,_Chayei_Sara.27:1":[true,"Underlined: the reason is that the Shabbos elevates everything to its root... it elevates all days and times to their roots..."]},
	]
}
